window.OMD_DATA = {
  version: "0.7.1",
  // Target coordinates are stored only as Cloudflare Worker secrets.
  pictures: [
    { title:"Kelly Family · 1989", file:"Kelly Family 1989.jpg", source:"https://commons.wikimedia.org/wiki/File:Kelly_Family_1989.jpg" },
    { title:"The Kelly Family · München", file:"The Kelly Family, München.jpg", source:"https://commons.wikimedia.org/wiki/File:The_Kelly_Family,_M%C3%BCnchen.jpg" },
    { title:"Michael Patrick Kelly · Live", info:"Leverkusener Jazztage · 2017", file:"Michael Patrick Kelly - Leverkusener Jazztage 2017-8339.jpg", source:"https://commons.wikimedia.org/wiki/File:Michael_Patrick_Kelly_-_Leverkusener_Jazztage_2017-8339.jpg" },
    { title:"Michael Patrick Kelly", file:"Michael Patrick Kelly.jpg", source:"https://commons.wikimedia.org/wiki/File:Michael_Patrick_Kelly.jpg" },
    { title:"Patricia Kelly · 1997", info:"Ostrava · 5. November 1997", file:"Patricia kelly ostrava 5 11 1997 adj.JPG", source:"https://commons.wikimedia.org/wiki/File:Patricia_kelly_ostrava_5_11_1997_adj.JPG" },
    { title:"Patricia Kelly", file:"Patricia-Kelly-(MS1411200026).jpg", source:"https://commons.wikimedia.org/wiki/File:Patricia-Kelly-(MS1411200026).jpg" },
    { title:"Angelo Kelly · 2002", info:"München · 2002", file:"Angelo Kelly (München, 2002).jpg", source:"https://commons.wikimedia.org/wiki/File:Angelo_Kelly_(M%C3%BCnchen,_2002).jpg" },
    { title:"Angelo Kelly · 2009", info:"Budapest · 2009", file:"Angelo Kelly 2009 Budapest.jpg", source:"https://commons.wikimedia.org/wiki/File:Angelo_Kelly_2009_Budapest.jpg" },
    { title:"Angelo Kelly · 2015", file:"Angelo-Kelly-2015.jpg", source:"https://commons.wikimedia.org/wiki/File:Angelo-Kelly-2015.jpg" },
    { title:"The Kelly Family · Hausboot", file:"Kelly Family Hausboot.jpg", source:"https://commons.wikimedia.org/wiki/File:Kelly_Family_Hausboot.jpg" }
  ],
  songs: [
    {id:"tkf-an-angel",artist:"The Kelly Family",title:"An Angel",url:"https://open.spotify.com/track/39tA7koBZwRzaes3ffpGz7"},
    {id:"tkf-fell-alien",artist:"The Kelly Family",title:"Fell In Love With An Alien",url:"https://open.spotify.com/track/7ByhqIL2dqk4W0jPTkWc9A"},
    {id:"tkf-cant-help",artist:"The Kelly Family",title:"I Can't Help Myself",url:"https://open.spotify.com/track/1lw9pi0WQjQ6RE0xpeG7eB"},
    {id:"tkf-nanana",artist:"The Kelly Family",title:"Nanana",url:"https://open.spotify.com/track/6GUHbWi00zgzYnyN6JALTQ"},
    {id:"tkf-because-love",artist:"The Kelly Family",title:"Because It's Love",url:"https://open.spotify.com/track/3yb2f6cpYyj2xmHvJl9QFg"},
    {id:"tkf-why",artist:"The Kelly Family",title:"Why Why Why",url:"https://open.spotify.com/track/6Xb4JiAmne14qC4l0N9Gaz"},
    {id:"tkf-first-time",artist:"The Kelly Family",title:"First Time",url:"https://open.spotify.com/track/2lmUPzub5JtcnsuK8Mlmji"},
    {id:"tkf-thunder",artist:"The Kelly Family",title:"Thunder",url:"https://open.spotify.com/track/7f1kGbPXDsPu5eP4y9zbE3"},
    {id:"tkf-every-baby",artist:"The Kelly Family",title:"Every Baby",url:"https://open.spotify.com/track/0XBbnaDR5SpgdCJqr1SJHi"},
    {id:"tkf-one-more-song",artist:"The Kelly Family",title:"One More Song",url:"https://open.spotify.com/track/11wV2F81H1s2lJGt16dbZJ"},
    {id:"tkf-i-feel-love",artist:"The Kelly Family",title:"I Feel Love",url:"https://open.spotify.com/track/1A2UgaY4LdCaJTgZeZNeXq"},
    {id:"tkf-santa-maria",artist:"The Kelly Family",title:"Santa Maria",url:"https://open.spotify.com/track/7gCbmLuFuFO1ydq4z9n6Sw"},
    {id:"tkf-eine-familie",artist:"The Kelly Family",title:"Eine Familie ist wie ein Lied",url:"https://open.spotify.com/track/4VBdh8kTG2vbvmm7KhSqQz"},
    {id:"tkf-angels-flying",artist:"The Kelly Family",title:"Angels Flying",url:"https://open.spotify.com/track/2L931kcK845PUlm04SIr9L"},
    {id:"tkf-over-hump",artist:"The Kelly Family",title:"Over The Hump",url:"https://open.spotify.com/track/7FDFGJlbkBFJSyOgY536i8"},
    {id:"tkf-so-many-troubles",artist:"The Kelly Family",title:"So Many Troubles",url:"https://open.spotify.com/track/7ed5dhPykqr5QB5MKRAl9E"},
    {id:"tkf-so-many-things",artist:"The Kelly Family",title:"So Many Things",url:"https://open.spotify.com/track/7AzUOAvfPZFoCKdPeLZLyh"},

    {id:"mpk-beautiful-madness",artist:"Michael Patrick Kelly",title:"Beautiful Madness",url:"https://open.spotify.com/track/0fGQJEKb7UGcBabIeDnqaB"},
    {id:"mpk-throwback",artist:"Michael Patrick Kelly",title:"Throwback",url:"https://open.spotify.com/track/6geycT57setrK5nARKXtNt"},
    {id:"mpk-the-one",artist:"Michael Patrick Kelly",title:"The One",url:"https://open.spotify.com/track/5eS3K28unzlfVchFSyJMrF"},
    {id:"mpk-wonders",artist:"Michael Patrick Kelly",title:"Wonders (feat. Rakim)",url:"https://open.spotify.com/track/5mD5zNNhbuP8O5itNTn4jl"},
    {id:"mpk-glorious",artist:"Michael Patrick Kelly",title:"Glorious",url:"https://open.spotify.com/track/54xYBeCgIVREZmEuAfP47K"},
    {id:"mpk-out-touch",artist:"Michael Patrick Kelly",title:"Out of Touch",url:"https://open.spotify.com/track/2VVuyTj4m1qaQOeWj62oqy"},
    {id:"mpk-oko-live",artist:"Michael Patrick Kelly",title:"O.K.O · Live",url:"https://open.spotify.com/track/54V4VJCwj8wj0SThUhZo1Z"},
    {id:"mpk-diamonds-live",artist:"Michael Patrick Kelly",title:"Diamonds & Metals · Live",url:"https://open.spotify.com/track/2EQmmlx7m8C7C7TGeHEUy1"},
    {id:"mpk-last-words-live",artist:"Michael Patrick Kelly",title:"Last Words · Live",url:"https://open.spotify.com/track/23RnbDPeRUQNRfo6sCpfTI"},

    {id:"pk-an-angel",artist:"Patricia Kelly",title:"An Angel",url:"https://open.spotify.com/track/7lrQc3V1NcgM1IivhorlEP"},
    {id:"pk-your-grace",artist:"Patricia Kelly",title:"Your Grace",url:"https://open.spotify.com/track/0OW88rDkk4TyX5VxQ0SpwQ"},
    {id:"pk-i-need-you",artist:"Patricia Kelly",title:"I Need You",url:"https://open.spotify.com/track/748NRy2D34NhCI4VgmTQd5"},

    {id:"ak-let-go",artist:"Angelo Kelly",title:"Let Go",url:"https://open.spotify.com/track/5ckNABhKwBi2NpHLd3dwfR"},
    {id:"ak-lord-dance",artist:"Angelo Kelly",title:"Lord Of The Dance",url:"https://open.spotify.com/track/3FvBRVxRHjmyzUHwsN61wZ"},
    {id:"ak-are-you-alive",artist:"Angelo Kelly",title:"Are You Alive",url:"https://open.spotify.com/track/3luF2zveWTwEaRd2a5KTyV"},
    {id:"ak-dont-know",artist:"Angelo Kelly",title:"Don't Know",url:"https://open.spotify.com/track/4puqGVTizPQhT0Ct7zs1bF"},
    {id:"ak-on-road",artist:"Angelo Kelly",title:"On The Road",url:"https://open.spotify.com/track/6D5wDEZwMFuIFJsnI8Si3r"},
    {id:"ak-coming-home-christmas",artist:"Angelo Kelly",title:"Coming Home For Christmas",url:"https://open.spotify.com/track/6ZIzgqfxPCI0wG1E6LAy7Y"},
    {id:"ak-singapore-london",artist:"Angelo Kelly",title:"Singapore To London · 2011 Version",url:"https://open.spotify.com/track/5WiGB1UFP0AWD7iLkvw7DR"},
    {id:"ak-finally-peace",artist:"Angelo Kelly",title:"Finally at Peace · 2009 Version",url:"https://open.spotify.com/track/2iP09fhDVlrTw4ax4UIQGh"},

    {id:"tkf-once-while-1994",artist:"The Kelly Family",title:"Once In A While",url:"https://open.spotify.com/track/1mKKkszQ2j1q0FtFpUdYgY"},
    {id:"tkf-life-hard",artist:"The Kelly Family",title:"Life Is Hard Enough",url:"https://open.spotify.com/track/1bLMkyl27NvAeyqX42llTd"},
    {id:"tkf-boys-town",artist:"The Kelly Family",title:"When The Boys Come Into Town",url:"https://open.spotify.com/track/2z3ybDM4OPUfvfxdCbOzAx"},
    {id:"tkf-baby-smile",artist:"The Kelly Family",title:"Baby Smile",url:"https://open.spotify.com/track/18zEjhpAYNIrF3cwZCGWgH"},
    {id:"tkf-rock-roll-soul",artist:"The Kelly Family",title:"Rock'n' Roll Stole My Soul",url:"https://open.spotify.com/track/0y0KKIkV1AjCv2ukkelYQi"},
    {id:"tkf-you-belong",artist:"The Kelly Family",title:"You Belong To Me",url:"https://open.spotify.com/track/7vgg2IGEo55eHJN6MQdk04"},
    {id:"tkf-fathers-nose-2019",artist:"The Kelly Family",title:"Father's Nose · 2019",url:"https://open.spotify.com/track/1K7QqGIRzVZcyaAUknQIau"},
    {id:"tkf-cover-road",artist:"The Kelly Family",title:"Cover The Road",url:"https://open.spotify.com/track/1MqJrPpsNHbnnMsitsQt97"},
    {id:"tkf-ill-swim",artist:"The Kelly Family",title:"I'll Swim, I'll Swim",url:"https://open.spotify.com/track/1dOqeDKxzkSRMzNxk2cGxu"},
    {id:"tkf-staying-alive",artist:"The Kelly Family",title:"Staying Alive",url:"https://open.spotify.com/track/4FmutE0PdOqylzCyS1n2zb"},
    {id:"tkf-hey-diddle",artist:"The Kelly Family",title:"Hey Diddle Diddle",url:"https://open.spotify.com/track/23wTr8TBnmlFJdFOKYdcj4"},
    {id:"tkf-ares-qui",artist:"The Kelly Family",title:"Ares Qui",url:"https://open.spotify.com/track/4y3haYw5V1RGVXz4eS1kHE"},
    {id:"tkf-break-free",artist:"The Kelly Family",title:"Break Free",url:"https://open.spotify.com/track/5EgS2d03vySXww1qRiVHx8"},
    {id:"tkf-wholl-come-1979",artist:"The Kelly Family",title:"Who'll Come With Me (David's Song) · 1979",url:"https://open.spotify.com/track/4WCOFB0MI88jHitX6a0poE"},
    {id:"tkf-agur-jaunak",artist:"The Kelly Family",title:"Agur Jaunak · 1979",url:"https://open.spotify.com/track/4LgMruy3fEWxE7nlMV6wXH"},
    {id:"tkf-schneegebirge",artist:"The Kelly Family",title:"Und in dem Schneegebirge · 1980",url:"https://open.spotify.com/track/7Lv3Qcm5Oy59PbYJcXc2lY"},
    {id:"tkf-alle-kinder",artist:"The Kelly Family",title:"Alle Kinder brauchen Freunde",url:"https://open.spotify.com/track/3B6dyUTOAb4w1iMqpkWOW4"},
    {id:"tkf-say-na-na",artist:"The Kelly Family",title:"Say Na Na",url:"https://open.spotify.com/track/0GFNtyIEZNDBfL5PYmYedB"},
    {id:"tkf-whats-matter",artist:"The Kelly Family",title:"What's A Matter You People",url:"https://open.spotify.com/track/0B8XOBN0F4n0yAupZrGL2R"},
    {id:"tkf-fire",artist:"The Kelly Family",title:"Fire",url:"https://open.spotify.com/track/1lfNClQbd59GQLPqVSdbZv"},
    {id:"tkf-baila",artist:"The Kelly Family",title:"Baila Mi Corazon",url:"https://open.spotify.com/track/1ImwXtsDdjIUyFlkgrsVK1"},
    {id:"tkf-star-county",artist:"The Kelly Family",title:"Star Of The County Down",url:"https://open.spotify.com/track/1gGmioeztQ6IZEf5cDATxe"},
    {id:"tkf-good-neighbor",artist:"The Kelly Family",title:"Good Neighbor",url:"https://open.spotify.com/track/0MNZcLhBYSE9hzHVPAAaoX"},
    {id:"tkf-come-back-2017",artist:"The Kelly Family",title:"Come Back To Me · 2017",url:"https://open.spotify.com/track/3JBewhA30JgEHWDi7g9qHF"},
    {id:"tkf-imagine",artist:"The Kelly Family",title:"Imagine",url:"https://open.spotify.com/track/19iZMEjqDc6PFUOKkW66II"},
    {id:"tkf-we-world",artist:"The Kelly Family",title:"We Are The World",url:"https://open.spotify.com/track/3Goq0p25Wr9SlGfX0yJgwP"},
    {id:"tkf-sweetest-angel",artist:"The Kelly Family",title:"Sweetest Angel",url:"https://open.spotify.com/track/5bYnog7t3s2TNmS9Zcq5sH"},
    {id:"tkf-roses-live95",artist:"The Kelly Family",title:"Roses Of Red · Live 1995",url:"https://open.spotify.com/track/7KwVUamT28uHVphnN71fnt"},
    {id:"tkf-wolf-live95",artist:"The Kelly Family",title:"The Wolf · Live 1995",url:"https://open.spotify.com/track/2DE1zRtLqisI3OZukayXHD"},
    {id:"tkf-red-shoes-live",artist:"The Kelly Family",title:"Red Shoes · Live",url:"https://open.spotify.com/track/2QsG67SbUvOewIBDlE0iu1"},
    {id:"tkf-boys-live-loreley",artist:"The Kelly Family",title:"When The Boys Come Into Town · Live",url:"https://open.spotify.com/track/1EuILCVJt4VLOF3bkbs7ys"},
    {id:"tkf-fire-live19",artist:"The Kelly Family",title:"Fire · Live 2019",url:"https://open.spotify.com/track/49HVPpzGdfILeDxf0zKASe"},
    {id:"tkf-we-dream-live19",artist:"The Kelly Family",title:"We Had A Dream · Live 2019",url:"https://open.spotify.com/track/07lWoDFuTaMXH3Ez2fguFa"},
    {id:"tkf-never-break-live19",artist:"The Kelly Family",title:"Never Gonna Break Me Down · Live 2019",url:"https://open.spotify.com/track/7n8nvPegHHdI2HTuCCeYBQ"},
    {id:"tkf-imagine-live",artist:"The Kelly Family",title:"Imagine · Live",url:"https://open.spotify.com/track/1afwJnpljBpGDL5i8bXxMo"},
    {id:"tkf-come-back-live",artist:"The Kelly Family",title:"Come Back To Me · Live",url:"https://open.spotify.com/track/0MWu8BHF5tmU1nUvv63eeS"},
    {id:"ak-never-too-late",artist:"Angelo Kelly",title:"Never Too Late",url:"https://open.spotify.com/track/41ttIdnkVLL90Zy0vmIvVO"},

    // Michael Patrick Kelly · erweiterter Solo-Pool
    {id:"mpk-run-free",artist:"Michael Patrick Kelly",title:"Run Free",url:"https://open.spotify.com/track/60Fzfp2K1eqr5Xpd2ynGwv"},
    {id:"mpk-traces",artist:"Michael Patrick Kelly",title:"Traces",url:"https://open.spotify.com/track/02K9rGknqp9ZPLVCHLs2X4"},
    {id:"mpk-wildflower",artist:"Michael Patrick Kelly",title:"Wildflower",url:"https://open.spotify.com/track/1bIeQdwWPefDKxD3VoZZ4W"},
    {id:"mpk-healing",artist:"Michael Patrick Kelly",title:"Healing",url:"https://open.spotify.com/track/0elPjsYk4jvar9KMvlI9wI"},
    {id:"mpk-rebellion",artist:"Michael Patrick Kelly",title:"Rebellion · mit R3HAB & Shaggy",url:"https://open.spotify.com/track/5XlZ6Z7MqWajjms2m2Qu7s"},
    {id:"mpk-higher-love",artist:"Michael Patrick Kelly",title:"Higher Love",url:"https://open.spotify.com/track/2q6y0b41YzVIGaLgWuqwTP"},
    {id:"mpk-friends-family",artist:"Michael Patrick Kelly",title:"Friends R Family",url:"https://open.spotify.com/track/7HRsRHFulGVmJSPGsDqA3q"},
    {id:"mpk-lazarus",artist:"Michael Patrick Kelly",title:"Lazarus",url:"https://open.spotify.com/track/0FzKoUVSv6G46dI9rmYH99"},
    {id:"mpk-fake-messiah",artist:"Michael Patrick Kelly",title:"Fake Messiah",url:"https://open.spotify.com/track/7hbM9mupJw1Kp0lWiUOkhc"},
    {id:"mpk-paragliding",artist:"Michael Patrick Kelly",title:"Paragliding",url:"https://open.spotify.com/track/5DdmLLOUUribxKXDBM8X3r"},
    {id:"mpk-ruah",artist:"Michael Patrick Kelly",title:"Ruah",url:"https://open.spotify.com/track/2ArpFiqGENYUSgf1DKQCk7"},
    {id:"mpk-walk-line",artist:"Michael Patrick Kelly",title:"Walk the Line",url:"https://open.spotify.com/track/2NYa61msWttiZfHn29cMBX"},
    {id:"mpk-dont-judas",artist:"Michael Patrick Kelly",title:"Don't Judas Me",url:"https://open.spotify.com/track/2T5h6S9hxW9jJ1iQocrSv2"},
    {id:"mpk-renegade",artist:"Michael Patrick Kelly",title:"Renegade",url:"https://open.spotify.com/track/3QAzybKGyjaSRHELpE3bH9"},
    {id:"mpk-thank-you",artist:"Michael Patrick Kelly",title:"Thank you",url:"https://open.spotify.com/track/5bM1YwgsfHSeepfz0RzYrq"},
    {id:"mpk-blurry-duet",artist:"Michael Patrick Kelly",title:"Blurry Eyes · Duett mit ClockClock",url:"https://open.spotify.com/track/5j3VRd9pLbxhu3jxj9Z2YP"},
    {id:"mpk-blurry-gromee",artist:"Michael Patrick Kelly",title:"Blurry Eyes · Gromee Remix",url:"https://open.spotify.com/track/3G8RmSe6XuEQpvJQnFVtSh"},
    {id:"mpk-friends-family-live23",artist:"Michael Patrick Kelly",title:"Friends R Family · Live 2023",url:"https://open.spotify.com/track/6XArjS31oijMbQaSf8hs0q"},

    // The Kelly Family · Klassiker, frühe Jahre und Live-Versionen
    {id:"tkf-fathers-nose-oth",artist:"The Kelly Family",title:"Father's Nose · Over The Hump",url:"https://open.spotify.com/track/5zo8CsbBjLlFA5MxPnOKaq"},
    {id:"tkf-calling-heaven",artist:"The Kelly Family",title:"Calling Heaven",url:"https://open.spotify.com/track/1iVNMloKwrdLsXzmfF4auD"},
    {id:"tkf-take-my-hand",artist:"The Kelly Family",title:"Take My Hand",url:"https://open.spotify.com/track/0mEHKVzfqPhySfaxuu8HW9"},
    {id:"tkf-the-rose",artist:"The Kelly Family",title:"The Rose",url:"https://open.spotify.com/track/6rnG1AaanQPzgnuyQffCKx"},
    {id:"tkf-last-rose-summer",artist:"The Kelly Family",title:"The Last Rose Of Summer",url:"https://open.spotify.com/track/6TvqTP903J1w4Np8s0eKqi"},
    {id:"tkf-swing-all-night",artist:"The Kelly Family",title:"Swing All Night",url:"https://open.spotify.com/track/3XXi3jChAe9sM4zB702zJu"},
    {id:"tkf-nanana-live95",artist:"The Kelly Family",title:"Nanana · Live 1995",url:"https://open.spotify.com/track/0ymr6sAo4xcCVThTYnBTtL"},
    {id:"tkf-fell-alien-live95",artist:"The Kelly Family",title:"Fell In Love With An Alien · Live 1995",url:"https://open.spotify.com/track/0uewRUtZA2y0z9mggBIJ1k"},
    {id:"tkf-ares-live95",artist:"The Kelly Family",title:"Ares Qui · Live 1995",url:"https://open.spotify.com/track/5eyTjDuLoTXTQaQ26iix4P"},
    {id:"tkf-cant-help-live96",artist:"The Kelly Family",title:"I Can't Help Myself · Live 1996",url:"https://open.spotify.com/track/4PbGlZdsf4qvCQnGwKfOyo"},
    {id:"tkf-fathers-nose-live17",artist:"The Kelly Family",title:"Father's Nose · Live",url:"https://open.spotify.com/track/5LtAkRgapTGC2NzZZQb83g"}
  ],
  weeklyRewards: [
    {title:"90s Time Machine",text:"Ein Kelly-Family-Live-Abend aus den 90ern.",query:"The Kelly Family live concert 1990s"},
    {title:"2000s Throwback",text:"Ein Konzert- oder TV-Mitschnitt aus den 2000ern.",query:"The Kelly Family live 2000 concert"},
    {title:"Paddy Live Special",text:"Michael Patrick Kelly live – heute bekommt die Solo-Ära die Bühne.",query:"Michael Patrick Kelly full concert live"},
    {title:"Angelo Live Special",text:"Ein längerer Angelo-Kelly-Live-Moment für die Wochenbelohnung.",query:"Angelo Kelly live concert"},
    {title:"Patricia Special",text:"Patricia Kelly live oder im Konzert – als Wochenabschluss.",query:"Patricia Kelly live concert"},
    {title:"Kelly Family Classics",text:"Eine längere Reise durch die großen Kelly-Family-Live-Klassiker.",query:"The Kelly Family live full concert classics"}
  ]
};
